# spring
spring:
  datasource:
    url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(vx9OWLu20TlanLx53aj/Qg==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

  redis:
    host: 192.168.0.146
    database: 0
    port: 6379
    timeout: 3000ms

  data:
    mongodb:
      uri: mongodb://192.168.0.146:27017/shop
    elasticsearch:
      cluster-name: d2cmall-es
      cluster-nodes: 192.168.0.146:9300

  rabbitmq:
    addresses: 192.168.0.146
    username: guest
    password: ENC(PRpwXXJMcX+sAqWS0oKFEQ==)

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.d2c.shop.service.modules.*.model
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
    sql-parser-cache: false
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    cache-enabled: false
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# shop-sdk
shop:
  sms:
    dahantc:
      account: ENC(UX8bZOr3oWSvBczS+9SsRA==)
      password: ENC(4uCdGxmEQtkdF+Pgl+GVkIE1xpUn36f0)