server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

# spring
spring:
  profiles:
    include: service-test

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            misfireThreshold: 100

#logging:
#  level:
#    root: debug